name: Publish
on:
  push:
    branches:
      - main
      - obsidian-publish-action # TODO
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tfausak/obsidian-publish-action@v1
        with:
          site: ${{ secrets.OBSIDIAN_SITE }}
          token: ${{ secrets.OBSIDIAN_TOKEN }}
